---
title: Quiz 1
format:
  stat20quiz-pdf:
      n-names: 3
      version: A
---

:::{.directionsbox}
Clearly write *True* or *False* on each blank line below.
:::

## {.tf}

The *mean* is a measure of [spread]{.vA .vB}[center]{.vC .vD}.

## {.tf}

The *mode* is a measure of skew.

\vspace{3mm}


##

What is the definition of a *p-value*?

- The probability that the null hypothesis is true.
- The probability of observing our test statistic or more extreme when the null hypothesis is true.
- The probability of observing our test statistic or more extreme when the null hypothesis is false.


:::{.directionsbox}
Fill in the checkbox of correct answer(s). Select all that apply.
:::

## {.select-all}

Which are the names of US states?

- California
- Italy
- Alabama
- Canada


:::{.directionsbox}
Fill in the checkbox of correct answer(s). Select all that apply.
:::
## {.select-all}

Which are measures of center?

- SD
* * *
- IQR
* * *
- Median

##

What is the definition of a *p-value*?

- The probability that the null hypothesis is true.
- The probability of observing our test statistic or more extreme when the null hypothesis is true.
- The probability of observing our test statistic or more extreme when the null hypothesis is false.
